apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  alertmanager.yml: |
    global: 
      resolve_timeout: 5m
      smtp_smarthost: 'xxx'
      smtp_from: 'xxxx'
      smtp_auth_username: 'xxxx'
      smtp_auth_password: 'xxx'

    receivers:
    - name: default-receiver
      email_configs:
      - to: "xxxxxn"

    route:
      group_interval: 1m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 1m
